### ISSUE TITLE
Remove OktaConfigurerBuilder

### ISSUE THREAD

**Issue by rwinch** [jadekler/git-java-okta-dsl#3]
To be consistent with the way Spring Security works with other extensions, we should remove `OktaConfigurerBuilder`. Instead add the properties to `OktaConfigurer`. Ideally the usage would look something like:

``` java
http
    .apply(okta())
        .keystorePath("saml/samlKeystore.jks")
        ...
```

**Comment by markdouglasswork** [comment]
I believe this should be good now with commit 8a8c71afa3a770024fc98ed2c9efd482d049c79f

**Comment by jeanbza** [comment]
👍
