### ISSUE TITLE
Provide hierarchical configuration

### ISSUE THREAD

**Issue by rwinch** [jadekler/git-java-okta-dsl#4]
Once #1 is done...Instead of placing every property on `OktaConfigurer` it might be good to provide some sort of hierarchy. For example:

``` java
http
    .apply(okta())
        .keystore()
            .location("classpath:/saml/keystore.jks")
            .password("secret")
            ...
            .and()
        .metadataFile("classpath:/saml/columbia-metadata.xml")
```

**Comment by jeanbza** [comment]
@markthemarkest As of 8a8c71afa3a770024fc98ed2c9efd482d049c79f, we have:

```
keystorePath
keystorePassword
defaultKey
defaultKeyPassword
metadataFilePath
protocol
hostname
basePath
entityId
```

What else do you think we should open up? Here are a couple of ideas, some of which prob suck:
- Okta discovery endpoints that are currently hardcoded:

```
new AntPathRequestMatcher("/saml/login/**")
new AntPathRequestMatcher("/saml/metadata/**")
new AntPathRequestMatcher("/saml/SSO/**")
new AntPathRequestMatcher("/saml/discovery/**")
```
- Passwords (currently only one allowed):

```
Map<String, String> passwords = new HashMap<>();
        passwords.put(defaultKey, defaultKeyPass);
```
- Logger

```
samlAuthenticationProvider.setSamlLogger(samlLogger);
```

Good argument can be made that these should be progressive enhancements, too.

**Comment by jeanbza** [comment]
edit: Once we identify the ones we want to open up, let's try grouping them into hierarchies as @rwinch suggested.

**Comment by markdouglasswork** [comment]
I've been thinking that the logger might make sense as well. I agree that grouping into hierarchies would be nice. I think that the SamlLogger makes a lot of sense to open up, I had been thinking the same thing. I hadn't considered the other two, the saml discovery paths make sense to me. I'm not sure if there's a use case for multiple passwords in the key manager currently, but if there is, I'd say we should certainly open it up.

**Comment by rwinch** [comment]
In terms of making other things configurable, I'd leave it to the bare minimum for now. We can always add things, but we cannot take them away (once it goes GA).

**Comment by jeanbza** [comment]
Good call, thanks @rwinch. @markthemarkest / Rob how do you feel about this?

```
.keystore()
  .storeFilePath("saml/colombia.jks")
  .password("colombia-password")
  .keyName("colombia")
  .keyPassword("colombia-password")
  .and()
.metadataFilePath("saml/colombia-metadata.xml")
.hostname("localhost:8443")
.basePath("/")
.entityId("com:example")
```

Some notes and questions on this:
- I'm excluding `protocol` and suggest we hardcode it to `https` right now because we haven't tried any other protocols, including base http. I'd like to try it before we allow it to see what the repercussions might be.
- `.keystore().password()` is the keystore passwords, whereas `.keystore().keyPassword()` is the password for the key referenced by `.keystore().keyName()`. Is there a way to make this clearer? Maybe we need a more deeply nested key object? Which leads to..
- The aforementioned `.keystore().keyName()/keyPassword()` is actually a map under the hood - you could have multiple keys with an associated password (I'm not sure what the mechanics of it look like, but it's possible in code). @rwinch in spring security DSL, what does an array look like? I'm talking about the equivalent of this in `.yml`:

```
  - keystore
    - keys
     - 
       - keyName1
       - keyPassword1
     - 
       - keyName2
       - keyPassword2
```

**Comment by markdouglasswork** [comment]
That example makes sense to me, I like it. Excluding basic http also seems reasonable, especially given that we haven't tested it. 

Nesting the structure one layer deeper seems like the most obvious way to make that distinction more clear. I'd be good with it. I don't mind exposing the ability for multiple keys and passwords, I'm just wondering if it's something we might want to wait to hear about a use case on.

**Comment by jeanbza** [comment]
See https://github.com/jadekler/git-java-okta-dsl/blob/477ccc21044471e2a3985c41fe53e015a4fca123/src/main/java/com/example/SecurityConfiguration.java#L21-L33 for current implementation:

```
        SecurityConfigurer securityConfigurerAdapter =
            okta()
                .keyStore()
                    .storeFilePath("saml/colombia.jks")
                    .password("colombia-password")
                    .keyname("colombia")
                    .keyPassword("colombia-password")
                    .and()
                .metadataFilePath("saml/colombia-metadata.xml")
                .protocol("https")
                .hostname("localhost:8443")
                .basePath("/")
                .entityId("com:example");
```
