### ISSUE TITLE
CSRF Refinements

### ISSUE THREAD

**Issue by rwinch** [jadekler/git-java-okta-dsl#5]
Ideally CSRF protection should be enabled. If necessary, we can have the DSL exclude specific endpoints from CSRF protection. For example:

``` java
http
    .csrf()
        .ignoringAntMatchers("/saml/login")
```

**Comment by markdouglasswork** [comment]
Enabled everywhere except /saml/SSO with commit f81396f1cd6994f29218967e8b063cabaf632916
