### ISSUE TITLE
Remove SAMLDslEntryPoint

### ISSUE THREAD

**Issue by rwinch** [jadekler/git-java-okta-dsl#7]
I don't think this class should be necessary since it is not exposed as a Bean

**Comment by markdouglasswork** [comment]
Hi Rob,

I think that setting it as the entry point with these lines exposes it as a Bean somehow:

``` java
            http
                .httpBasic()
                .authenticationEntryPoint(samlEntryPoint)
```

I have attached the stacktrace for the exception we encounter when running with the original SAMLEntryPoint. When I do not set this as the entry point as above, everything starts up and login functions. However, the app doesn't redirect properly, but instead returns a 403 unless the user navigates directly to /saml/login.
[nosuchbean..txt](https://github.com/jadekler/git-java-okta-dsl/files/231070/nosuchbean.txt)

**Comment by jeanbza** [comment]
@rwinch ping ^

**Comment by jeanbza** [comment]
Moved as part of https://github.com/jadekler/spring-security-saml-dsl/issues/1
